### ISSUE TITLE
페어 리뷰(#1)

### ISSUE THREAD

**Issue by uha9218** [openmpy/mission-01#15]
## DTO 
* 각 기능 별로 나누어서 Dto를 생성해 필요한 기능들을 추가한 부분 보고 배웠습니다!  
* Timestamp entity를 따로 생성하지 않고 수환님 코드처럼 Dto에 합치는 것이 코드 해석에 도움이 될 것 같습니다.

```java
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Getter
public class ReadBoardResponseDto {

    private Long id;
    private String title;
    private String writer;
    private String contents;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
    private LocalDateTime createdAt;

    public static ReadBoardResponseDto fromEntity(Board board) {
        return ReadBoardResponseDto.builder()
                .id(board.getId())
                .title(board.getTitle())
                .writer(board.getWriter())
                .contents(board.getContents())
                .createdAt(board.getCreatedAt())
                .build();
    }
}
``` 
* 이코드에서 생성자를 사용하는게 아닌 따로 메서드를 사용해서 객체를 초기화하는 이유가 따로 있을까요?

## Service
```java
    @Transactional(readOnly = true)
    public ReadBoardResponseDto read(Long id) {
        Board board = boardRepository.findById(id).orElseThrow(() ->
                new CustomBoardException(INVALID_BOARD_ID.getMessage())
        );

        return ReadBoardResponseDto.fromEntity(board);
    }

``` 
* Transaction개념을 처음 배워서 @Transactional은 SimpleJpaRepository에 메서드가 없어 영속성 관리가 필요한 메서드에 붙이는 키워드 정도로만 이해하고 있었는데 수환님 덕분에 읽기 메서드들은  @Transactional(readOnly=true) 어노테이션이 필요하다는 사실을 알았습니다 ദ്ദിᐢ. .ᐢ₎

## global 
* exception 처리 부분에서 CustomValidationAdvice 클래스가 필요한 이유를 알 수 있을까요?

## Controller
```java
    @PutMapping("/{id}")
    public ResponseEntity<?> editBoard(@PathVariable Long id,
                                       @RequestBody @Valid EditBoardRequestDto requestDto,
                                       BindingResult bindingResult) {
        EditBoardResponseDto responseDto = boardService.edit(id, requestDto);
        return ResponseEntity.ok().body(
                new ResponseDto<>(true, "게시글 수정", responseDto)
        );
    }
``` 
* ResponseEntity 를 수환님 덕분에 처음 알게되었습니다. ദ്ദിദ്ദി
* ResponseEntity 를 사용하면 상태 코드, 메세지 등이 직관적으로 보여서 코드 이해가 쉬워지는 것 같습니다

api 명세서를 포함한 readme파일 부터 코드까지 배울 부분 밖에 안보이는 것 같습니다
보완 부분을 찾아서 의견 공유를 하고 싶은데 제 실력 문제로 얻어가기만 합니다 ✍️
다음 레벨 과제 잘부탁드립니다!

**Comment by openmpy** [comment]
Timestamp entity를 따로 생성하지 않고 수환님 코드처럼 Dto에 합치는 것이 코드 해석에 도움이 될 것 같습니다.
- 유하님이 하신 거처럼 분리 해주는게 원래는 정석인데 테이블이 한개여서 저는 합쳐서 작성했습니다.

이코드에서 생성자를 사용하는게 아닌 따로 메서드를 사용해서 객체를 초기화하는 이유가 따로 있을까요?
- 생성자로 처리 하는게 좀 더 편할거 같네요. 감사합니다!

exception 처리 부분에서 CustomValidationAdvice 클래스가 필요한 이유를 알 수 있을까요?
- validation을 사용해서 예외처리를 한번에 하려고 작성 했습니다. 안그러면 controller단에서 BindingResult로 일일이 다 작성 해줘야해서.. 중복된 코드가 많이 생기더라구요.. 그래서 aop 적용해서 작성 해봤습니다.
